name: scroll_datetime_picker
description: A Scrollable DateTimePicker, inspired by the CupertinoDatePicker but with more extensive customizable features.
version: 0.0.4
homepage: https://ad.auliyaa.com
repository: https://github.com/dhiyaaulauliyaa/scroll_datetime_picker
issue_tracker: https://github.com/dhiyaaulauliyaa/scroll_datetime_picker/issues
topics:
  - widget
  - datetime
  - picker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter: